name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: S3 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci --no-audit --ignore-scripts
      - name: Build
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: |
          aws s3 sync \
            --delete \
            --cache-control 'public, max-age=3600, s-maxage=86400, no-transform' \
            build s3://react-playground.vlazaro.es